- name: Install openshift distributed tracing Operator
  k8s:
    state: present
    definition: "{{ lookup('template', 'subs-jaeger.yml.j2') }}"

- name: Wait for openshift distributed tracing CRD to exist
  k8s_info:
    api_version: "apiextensions.k8s.io/v1"
    kind: CustomResourceDefinition
    name: "{{ item }}"
  loop: "{{ jaeger_expected_crds }}"
  register: crds
  until: crds.resources|length > 0
  retries: 30
  delay: 10
