apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-distributed-tracing-og
  namespace: openshift-distributed-tracing
spec:
  targetNamespaces:
  - openshift-distributed-tracing
